# Generated by Django 5.2.5 on 2025-11-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Panel_Productos', '0001_initial'),
        ('Panel_Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Bodega')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'bodega',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('S', 'Salida'), ('T', 'Transferencia'), ('A', 'Ajustes'), ('D', 'Devoluciones')], default='I', max_length=1)),
                ('cantidad', models.PositiveIntegerField()),
                ('lote', models.CharField(blank=True, max_length=10, null=True)),
                ('serie', models.CharField(blank=True, max_length=10, null=True)),
                ('fechaVencimiento', models.DateField(blank=True, null=True)),
                ('doc_referencia', models.CharField(max_length=10)),
                ('motivo', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, max_length=500)),
                ('bodega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventario.bodega')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Panel_Productos.producto')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Panel_Proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimiento',
            },
        ),
    ]
