# Generated by Django 5.2.7 on 2025-10-20 20:43

import Panel_Proveedores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rut_nif',
            field=models.CharField(max_length=20, unique=True, validators=[Panel_Proveedores.validators.validate_rut_chile_or_nif], verbose_name='RUT / NIF'),
        ),
    ]
