# Generated by Django 5.2.7 on 2025-11-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2025-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
