# Generated by Django 5.2.7 on 2025-10-20 21:07

import Panel_Proveedores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Productos', '0002_alter_categoria_nombre_alter_unidadmedida_nombre'),
        ('Panel_Proveedores', '0002_alter_proveedor_rut_nif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rut_nif',
            field=models.CharField(help_text='Formato: 12345678-9 o 12345678-K', max_length=20, unique=True, validators=[Panel_Proveedores.validators.validate_rut_chile], verbose_name='RUT'),
        ),
        migrations.AddConstraint(
            model_name='ofertaproveedor',
            constraint=models.CheckConstraint(condition=models.Q(('lead_time_dias__gte', 0)), name='oferta_lead_time_no_negativo'),
        ),
    ]
