# Generated by Django 5.2.5 on 2025-10-20 03:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('CH', 'Chocolates'), ('GA', 'Galletas'), ('AL', 'Alfajores'), ('CO', 'Confitería'), ('BO', 'Bombonería'), ('CA', 'Caramelos'), ('GO', 'Gomitas'), ('PA', 'Paletas'), ('MA', 'Masmelos'), ('SA', 'Snacks dulces')], default='CH', max_length=3, unique=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('UN', 'Unidad'), ('CAJA', 'Caja'), ('KG', 'Kilogramos'), ('PAQ', 'Paquete'), ('BOL', 'Bolsa'), ('DOC', 'Docena'), ('BAN', 'Bandeja'), ('LT', 'Litro'), ('GR', 'Gramos'), ('DIS', 'Display'), ('PRO', 'UM Profe')], default='UN', max_length=4, unique=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidad_medida',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=15, unique=True, verbose_name='SKU')),
                ('ean_upc', models.PositiveIntegerField(unique=True, verbose_name='Código EAN/UPC')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=300, verbose_name='Descripción')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('factor_conversion', models.PositiveIntegerField(default=1, verbose_name='Factor de Conversión')),
                ('costo_estandar', models.PositiveIntegerField(blank=True, verbose_name='Costo Estandar')),
                ('costo_promedio', models.PositiveIntegerField(blank=True, verbose_name='Costo Promedio')),
                ('precio_venta', models.PositiveIntegerField(blank=True, verbose_name='Precio de Venta')),
                ('impuesto_iva', models.PositiveSmallIntegerField(default=19, verbose_name='Porcentaje de Iva (%)')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.PositiveIntegerField(blank=True, verbose_name='Stock Máximo')),
                ('punto_reorden', models.PositiveIntegerField(blank=True, verbose_name='Punto de Reorden')),
                ('perishable', models.BooleanField(default=False, verbose_name='¿Es perecible?')),
                ('control_por_lote', models.BooleanField(default=False, verbose_name='Control por lote')),
                ('control_por_serie', models.BooleanField(default=False, verbose_name='Control por número de serie')),
                ('imagen_url', models.URLField(blank=True, max_length=300, verbose_name='URL Imagen')),
                ('ficha_tecnica_url', models.URLField(blank=True, max_length=300, verbose_name='URL de la Ficha Técnica')),
                ('stock_actual', models.PositiveIntegerField(verbose_name='Stock Actual')),
                ('alerta_bajo_stock', models.CharField(max_length=2, verbose_name='Alerta de Bajo Stock')),
                ('alerta_por_vencer', models.CharField(max_length=2, verbose_name='Alerta de Vencimiento')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Panel_Productos.categoria')),
                ('uom_compra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos_compra', to='Panel_Productos.unidadmedida')),
                ('uom_venta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos_venta', to='Panel_Productos.unidadmedida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
