# Generated by Django 5.2.7 on 2025-11-19 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_abreviado', models.CharField(default='CH', max_length=3, unique=True, verbose_name='Nombre Abreviado')),
                ('nombre_completo', models.CharField(default='Chocolate', max_length=20, unique=True, verbose_name='Nombre Completo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_abreviado', models.CharField(default='UN', max_length=4, unique=True, verbose_name='Nombre Abreviado')),
                ('nombre_completo', models.CharField(default='Unidad', max_length=20, unique=True, verbose_name='Nombre Completo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidad_medida',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=15, unique=True, verbose_name='SKU')),
                ('ean_upc', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Código EAN/UPC')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=300, verbose_name='Descripción')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('factor_conversion', models.PositiveIntegerField(default=1, verbose_name='Factor de Conversión')),
                ('costo_estandar', models.PositiveIntegerField(blank=True, verbose_name='Costo Estandar')),
                ('costo_promedio', models.PositiveIntegerField(blank=True, verbose_name='Costo Promedio')),
                ('precio_venta', models.PositiveIntegerField(blank=True, verbose_name='Precio de Venta')),
                ('impuesto_iva', models.PositiveSmallIntegerField(default=19, verbose_name='Porcentaje de Iva (%)')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.PositiveIntegerField(blank=True, verbose_name='Stock Máximo')),
                ('punto_reorden', models.PositiveIntegerField(blank=True, null=True, verbose_name='Punto de Reorden')),
                ('perishable', models.BooleanField(default=False, verbose_name='¿Es perecible?')),
                ('control_por_lote', models.BooleanField(default=False, verbose_name='Control por lote')),
                ('control_por_serie', models.BooleanField(default=False, verbose_name='Control por número de serie')),
                ('imagen_url', models.URLField(blank=True, max_length=300, verbose_name='URL Imagen')),
                ('ficha_tecnica_url', models.URLField(blank=True, max_length=300, verbose_name='URL de la Ficha Técnica')),
                ('stock_actual', models.PositiveIntegerField(verbose_name='Stock Actual')),
                ('alerta_bajo_stock', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2)),
                ('alerta_por_vencer', models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='SI', max_length=2)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Panel_Productos.categoria')),
                ('uom_compra', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos_compra', to='Panel_Productos.unidadmedida')),
                ('uom_venta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos_venta', to='Panel_Productos.unidadmedida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
