# Generated by Django 5.2.5 on 2025-10-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='alerta_bajo_vencer',
            new_name='alerta_por_vencer',
        ),
    ]
