# Generated by Django 5.2.5 on 2025-10-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_promedio',
            field=models.PositiveIntegerField(blank=True, default=0.0, verbose_name='Costo Promedio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('CH', 'Chocolates'), ('GA', 'Galletas'), ('AL', 'Alfajores'), ('CO', 'Confitería'), ('BO', 'Bombonería'), ('CA', 'Caramelos'), ('GO', 'Gomitas'), ('PA', 'Paletas'), ('MA', 'Masmelos'), ('SA', 'Snacks dulces')], default='CH', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(choices=[('UN', 'Unidad'), ('CAJA', 'Caja'), ('KG', 'Kilogramos'), ('PAQ', 'Paquete'), ('BOL', 'Bolsa'), ('DOC', 'Docena'), ('BAN', 'Bandeja'), ('LT', 'Litro'), ('GR', 'Gramos'), ('DIS', 'Display'), ('PRO', 'UM Profe')], default='UN', max_length=4, unique=True),
        ),
    ]
