# Generated by Django 5.2.5 on 2025-10-06 03:04
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Productos', '0001_initial'),
    ]

    # No-op: el campo ya se llama alerta_por_vencer en el modelo/DB.
    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
