# Generated by Django 5.2.5 on 2025-11-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ean_upc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Código EAN/UPC'),
        ),
    ]
