# Generated by Django 5.2.7 on 2025-11-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Productos', '0002_alter_categoria_nombre_alter_unidadmedida_nombre'),
        ('Panel_Productos', '0002_producto_costo_promedio_alter_categoria_nombre_and_more'),
        ('Panel_Productos', '0002_rename_alerta_bajo_vencer_producto_alerta_por_vencer'),
    ]

    operations = [
    ]
