# Generated by Django 5.2.7 on 2025-11-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Productos', '0002_rename_alerta_bajo_vencer_producto_alerta_por_vencer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='costo_promedio',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Costo Promedio'),
        ),
    ]
