# Generated by Django 5.2.7 on 2025-10-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Productos', '0002_alter_categoria_nombre_alter_unidadmedida_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(choices=[('UN', 'Unidad'), ('CAJA', 'Caja'), ('KG', 'Kilogramos'), ('PAQ', 'Paquete'), ('BOL', 'Bolsa'), ('DOC', 'Docena'), ('BAN', 'Bandeja'), ('LT', 'Litro'), ('GR', 'Gramos'), ('DIS', 'Display')], default='UN', max_length=4, unique=True),
        ),
    ]
