# Generated by Django 5.2.7 on 2025-10-19 09:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Area')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Rol')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Email')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Telefono')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('B', 'Bloqueado')], default='A', max_length=1)),
                ('mfa_habilitado', models.BooleanField(default=False, verbose_name='MFA_Habilitado')),
                ('ultimo_acceso', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('sesiones_activas', models.PositiveIntegerField(blank=True, default=0)),
                ('observaciones', models.TextField(blank=True, max_length=200, verbose_name='Observaciones')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Panel_Usuarios.area')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Panel_Usuarios.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
