# Generated by Django 5.2.7 on 2025-10-19 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sesiones_activas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
