# Generated by Django 5.2.7 on 2025-11-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, verbose_name='Telefono'),
        ),
    ]
