# Generated by Django 5.2.7 on 2025-11-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='puede_gestionar_proveedores',
            field=models.BooleanField(default=False),
        ),
    ]
