# Generated by Django 5.2.7 on 2025-10-19 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Usuarios', '0002_alter_usuario_sesiones_activas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sesiones_activas',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
