# Generated by Django 5.2.7 on 2025-10-19 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Usuarios', '0003_alter_usuario_sesiones_activas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
