# Generated by Django 5.2.7 on 2025-10-19 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Usuarios', '0004_alter_usuario_ultimo_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sesiones_activas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
