# Generated by Django 5.2.7 on 2025-11-06 04:18

import Panel_Usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Usuarios', '0004_make_fk_nullable'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', Panel_Usuarios.models.UsuarioManager()),
            ],
        ),
    ]
