# Generated by Django 5.2.7 on 2025-10-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Usuarios', '0005_alter_usuario_sesiones_activas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, verbose_name='Observaciones'),
        ),
    ]
