# Generated by Django 5.2.7 on 2025-10-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panel_Usuarios', '0006_alter_usuario_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
